//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goldbach.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Goldbach.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1, 2, 2
        ///2, 3, 1
        ///3, 5, 2
        ///4, 7, 2
        ///5, 11, 4
        ///6, 13, 2
        ///7, 17, 4
        ///8, 19, 2
        ///9, 23, 4
        ///10, 29, 6
        ///11, 31, 2
        ///12, 37, 6
        ///13, 41, 4
        ///14, 43, 2
        ///15, 47, 4
        ///16, 53, 6
        ///17, 59, 6
        ///18, 61, 2
        ///19, 67, 6
        ///20, 71, 4
        ///21, 73, 2
        ///22, 79, 6
        ///23, 83, 4
        ///24, 89, 6
        ///25, 97, 8
        ///26, 101, 4
        ///27, 103, 2
        ///28, 107, 4
        ///29, 109, 2
        ///30, 113, 4
        ///31, 127, 14
        ///32, 131, 4
        ///33, 137, 6
        ///34, 139, 2
        ///35, 149, 10
        ///36, 151, 2
        ///37, 157, 6
        ///38, 163, 6
        ///39, 167, 4
        ///40, 173, 6
        ///41, 179, 6
        ///42, 181, 2
        ///43, 191, 10
        ///44, 193, 2
        ///45, 197, 4
        ///46, 199 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string primes {
            get {
                return ResourceManager.GetString("primes", resourceCulture);
            }
        }
    }
}
